### ISSUE TITLE
app crashed & restarted automatically

### ISSUE THREAD

**Issue by HikaruIchijyo** [CrepeTF/Takoyomi#30]
### Steps to reproduce

Dunno how toreproduce but i was batch migrating some sources suddenly it crashed & wen i opened it again it was still on migrating screen & on infinite loading

### Expected behavior

Shouldnt crash

### Actual behavior

Restarted

### Crash logs

2022-04-09 12:18:24.751 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:236)
	├ android.app.ActivityThread.main(ActivityThread.java:8031)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
> Failed to load next catalogue page!
java.io.IOException: Failed to bypass Cloudflare
	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:16)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:8)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:16)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:5)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:2)
	at rx.Subscriber.setProducer(Subscriber.java:8)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
	at rx.Subscriber.setProducer(Subscriber.java:6)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda-0(OkHttpExtensions.kt:4)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.$r8$lambda$V4FTlhE0zGLykdl_yqVQNonk7gs(Unknown Source:0)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(Unknown Source:4)
	at rx.Observable.unsafeSubscribe(Observable.java:2)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
	at rx.Observable.unsafeSubscribe(Observable.java:2)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
	at rx.Observable.subscribe(Observable.java:25)
	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:4)
	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:1)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:8)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-04-09 12:18:24.752 W/BrowseSourceController: > (source.id: 3112384885023225761, source.name: Kissmanga.in)
2022-04-09 12:29:59.463 E/MangaPresenter: 	├ exh.log.LoggingKt.xLogE(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.manga.MangaPresenter$fetchMangaFromSource$1.invokeSuspend(MangaPresenter.kt:14)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	├ kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	├ kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	└ kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Error getting manga details
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@8864489

2022-04-09 12:37:26.967 E/MangaPresenter: 	├ exh.log.LoggingKt.xLogE(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.manga.MangaPresenter$fetchMangaFromSource$1.invokeSuspend(MangaPresenter.kt:14)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	├ kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	├ kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	└ kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Error getting manga details
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@2679125

### Tachiyomi version

3.17

### Android version

11

### Device

redmi note 10s

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by HikaruIchijyo** [comment]
Nvm ig there is nothing in logs so no helping in opening an issue
